version: "3.8"

services:

  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    networks:
      - integration-apisix-net

  apisix-container:
    image: apache/apisix:latest
    ports:
      - "9080:9080"
    networks:
      - integration-apisix-net
    volumes:
      - ./apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    environment:
      - ETCD_HOST=http://etcd:2379

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - integration-apisix-net
    command: start-dev

networks:
  integration-apisix-net:
    # driver: bridge
    driver: bridge

volumes:
  keycloak_data:
  apisix_data:
